### ISSUE TITLE
dashboard output (single and multiple)

### ISSUE THREAD

**Issue by damilarekila** [zuri-training/Excel_comp_Team108_DataSYNC#10]
return results for compare and convert actions, single and multiple screens. 

compare return should contain radio button options to choose which one of four possible out output options from project brief. 

delievrables: good ui, wireframes, lo fi and hi fi designs.

**Comment by DigitalRhythm** [comment]
Done with this.

I completed the wireframe,  LoFi and, HiFi designs.

Output Page
https://www.figma.com/file/Ie8A81XMRsHiodqFwaeTO8/Team_108_excel_comp?node-id=847%3A13632

I made the output action bar icons a component and designed their hover states using variants
https://www.figma.com/file/Ie8A81XMRsHiodqFwaeTO8/Team_108_excel_comp?node-id=1000%3A21076

The action bar icons are, zoom, protect, last page, first page, next page, and, previous page
https://www.figma.com/file/Ie8A81XMRsHiodqFwaeTO8/Team_108_excel_comp?node-id=847%3A14302

**Comment by damilarekila** [comment]
good job

**Comment by DigitalRhythm** [comment]
I also worked on the copies for:
Research document
https://docs.google.com/document/d/1vW1Q0kR8dbjQL5CaEjanc7PFkbSVpzpdUubhzHa8k8Y/edit?usp=sharing

Landing Page
Unauthenticated Users - https://www.figma.com/file/Ie8A81XMRsHiodqFwaeTO8/Team_108_excel_comp?node-id=895%3A13936
Authenticated Users - https://www.figma.com/file/Ie8A81XMRsHiodqFwaeTO8/Team_108_excel_comp?node-id=895%3A14000

Script for our first presentation
https://docs.google.com/document/d/1wz4S8txPx_DeSCIxs7PlX4n6hGxUbfeg6xzK5EKjZkk/edit?usp=drivesdk

Contributed on our ideas and decision board
https://docs.google.com/document/d/1zHq4br1bAnp3mToaktqiAHoxoAC5iBfDjJcZz8JJnJc/edit?usp=sharing

Worked on our 1st Presentation Slides
https://docs.google.com/presentation/d/1lyYQQWrnOKNjqVEF5UvYkHuKUwk1BQDOW6z47kaVPA4/edit?usp=drivesdk

Presented our 1st Presentation
https://drive.google.com/file/d/1nf-1si0vW89wGTXYES0g3HdeNVenvJuO/view?usp=sharing

As Assistant Team Lead (Product Design), I contributed in assigning, and following up on tasks, passing accurate information and ensuring positive outcomes from our team activities.
