### ISSUE TITLE
mission statement, contact us

### ISSUE THREAD

**Issue by damilarekila** [zuri-training/Excel_comp_Team108_DataSYNC#3]
states our mission, what goals our solution seeks to achieve

**Comment by Zulaiha6568** [comment]
My name is Zulaiha Muhamad, As a product designer in my team, I was part of the people that worked on the Interview script, and I was also assigned to design a Mission statement page that will enable the user to know the mission of DATASYN and also a Contact Us page, which will be the link between the user and DATASYN in which the user can send a message for complaining or any comment about DATASYN.
Wireframes, LO-FI, (https://www.figma.com/file/Ie8A81XMRsHiodqFwaeTO8/Team_108_excel_comp?node-id=1049%3A22154), and HI-FI (https://www.figma.com/file/Ie8A81XMRsHiodqFwaeTO8/Team_108_excel_comp?node-id=0%3A1) designs were delivered within a deadline. 
I am now, waiting for further assigned tasks after the final presentation for a final appearance.

**Comment by damilarekila** [comment]
good job zulaiha
