### ISSUE TITLE
About us page and pricing page

### ISSUE THREAD

**Issue by damilarekila** [zuri-training/Excel_comp_Team108_DataSYNC#4]
Contains information on what we do as a team and how we achieved this team.

Deliverables: wireframe, lowfi, hifi designs
Deadline: Thursday, 8/04/2022

**Comment by baize1246f** [comment]
I resorted to behance, dribbble and google for inspiration then i was able sketch my wireframe after which i created low fi and hi fidelity screens. All thanks to zuri for the oppurtunity to participate in the project phase and also to my group members. I created the different plans and offers which are standard, deluxe and premium with their respective prices then I also put out information about the project we worked on and our website features.

**Comment by baize1246f** [comment]
https://www.figma.com/file/qyJRGdz5lGEgGG7WU7OrWJ/Untitled?node-id=0%3A1   

My name is Wisdom Egbune. The link above is the link to access my work done on my project team.

**Comment by damilarekila** [comment]
good job
