### ISSUE TITLE
error 404, loading, success page.

### ISSUE THREAD

**Issue by damilarekila** [zuri-training/Excel_comp_Team108_DataSYNC#6]
all three pages should be modals or popups, loading page should have activity.

deliverables: good UI designs wireframes lo fi and hi fi designs.

**Comment by Phemy-dev** [comment]
On being assigned the role of delivering the error 404, loading and success page. I designed the 3 pages in wireframe, low fidelity and high fidelity versions for final development by the developers.

**Comment by damilarekila** [comment]
good

**Comment by Phemy-dev** [comment]
I designed the wireframes and High fidelity designs for the error, loading and success page

https://www.figma.com/file/Ie8A81XMRsHiodqFwaeTO8/Team_108_excel_comp?node-id=712%3A4354


https://www.figma.com/file/Ie8A81XMRsHiodqFwaeTO8/Team_108_excel_comp?node-id=716%3A4358


https://www.figma.com/file/Ie8A81XMRsHiodqFwaeTO8/Team_108_excel_comp?node-id=712%3A4348
