### ISSUE TITLE
share page, protect page

### ISSUE THREAD

**Issue by damilarekila** [zuri-training/Excel_comp_Team108_DataSYNC#7]
Share link or file to other platforms, messaging channels and social media platforms, drives etc. 

Deliverables: good UI designs, wireframes, low fi and hi fi designs.

**Comment by Coco326** [comment]
Done ✔ 
Created the share modal
Created the wireframe, low-fi and hi-fi  design for the document protect page.

**Comment by damilarekila** [comment]
good job

**Comment by Coco326** [comment]
Thank you
