### ISSUE TITLE
downwload page, convert page

### ISSUE THREAD

**Issue by damilarekila** [zuri-training/Excel_comp_Team108_DataSYNC#8]
downlaoad page should contain different file format to choose from. 

convert page, users can convert file from original format to another select format. 

Deliverable: good ui design, wireframes, lofi and hi fi designs.

**Comment by belloaisha1467** [comment]
I have completed the designs i.e the wireframes, Lofi and Hifi designs for the convert and download pages.

**Comment by belloaisha1467** [comment]
For the convert page, I designed a screen where users can drag or upload the file to be converted and also get to choose the file which they want it converted too
For the download page, I made a design containing different options for users to choose where they want their converted file to download too.

**Comment by belloaisha1467** [comment]
For the convert page, I designed a screen where users can drag or upload the file to be converted and also get to choose the format they want their file converted too. 
For the download page, I made a design containing different options for users to choose where they want their converted file downloaded too.

**Comment by belloaisha1467** [comment]
Designing different format for the users for both the convert and download screen was done to prevent limiting users to a particular option. That way, our users get to have a say in the choice of file format they want.

**Comment by damilarekila** [comment]
good job
